spring:
  application:
    name: tlias-web-management
  #配置数据库的连接信息
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/tlias
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    oracle:
      jdbc-url: jdbc:oracle:thin:@localhost:1521:tlias
      username: tlias_user
      password: 123456
      driver-class-name: oracle.jdbc.OracleDriver
  servlet:
    multipart:
      max-file-size: 10MB #最大单个文件大小
      max-request-size: 100MB #最大请求大小（包括所有文件和表单数据）
  data:
    redis:
      port: 6379
      host: localhost
      password: 123456
      database: 9
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #开启驼峰命名映射开关
  #配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: taxing-java
    region: cn-beijing
